version: '3'
services:
  client:
    build: ./client
    volumes:
    - ./client:/opt/app
    - ./opt/app/node_modules
    ports:
    - 8080:8080
    links:
    - api

  api:
    build: ./server
    volumes:
    - ./server:/opt/app
    - ./opt/app/node_modules
    ports:
    - 5000
